version: '3.5'

services:
    postgres:
        image: postgres:15-alpine
        container_name: mamushin_db
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
          - "5005:5432"
    backend:
        image: mamushin_hw_arc:v1
        container_name: mamushin_service
        build: .
        ports:
            - "5000:80"
        links:
            - "postgres:database"
        environment:
            DB_HOST: "database"
            DB_PORT: "5432"
            ASPNETCORE_ENVIRONMENT: "Stg"
            